name: Publish SharpFileSystem on NuGet

on:
  push:
    tags:
      - 'v*'
    paths: [ 'src/SharpFileSystem/**' ]
  workflow_dispatch:

env:
  NET_VERSION: '7.x'
  PROJECT_NAME: src/SharpFileSystem
  PROJECT_FILE: SharpFileSystem.csproj
  RELEASE_NAME: SharpFileSystem

jobs:
  publish:
    name: Publish on NuGet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET SDK ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.NET_VERSION }}
        dotnet-quality: 'ga'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion # id to later be referenced
      uses: gittools/actions/gitversion/execute@v0

    - name: Display GitVersion outputs (step output)
      run: |
          echo "NuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"

    - name: Build (dotnet)
      run: dotnet build --configuration Release ${{ env.PROJECT_NAME }}/${{ env.PROJECT_FILE }}

    - name: Test (dotnet)
      run: dotnet test --no-restore --verbosity normal ${{ env.PROJECT_NAME }}/${{ env.PROJECT_FILE }}

    - name: Pack (dotnet)
      run: dotnet pack ${{ env.PROJECT_NAME }}/${{ env.PROJECT_FILE }} --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}

    - name: View Pack
      run: ls -la ./nuget-packages/*.nupkg
